version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: lambci/lambda:build-python3.8

references:
  commands:
    install_sls: &install_sls
      name: Install Serverless
      command: |
        curl -sL https://rpm.nodesource.com/setup_10.x | bash -
        yum install -y nodejs
        curl -o- -L https://yarnpkg.com/install.sh | bash
        npm install -g yarn
    install_dependencies: &install_dependencies
      name: Install dependencies
      command: |
        export PYTHONPATH=./
        python3 -m venv venv
        . venv/bin/activate
        pip install -r requirements-dev.txt
        yarn install

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - run: *install_sls
      - run: *install_dependencies
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - ./*
  lint:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: ~/workspace
      - run: *install_sls
      - run: *install_dependencies
      - run:
          name: Lint
          command: yarn lint

workflows:
  version: 2
  build-deploy-flow:
    jobs:
      - setup:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - setup
          filters:
            tags:
              only: /.*/