service: db

provider:
  name: aws
  region: ${file(serverless-common.yml):region}
  stage: ${file(serverless-common.yml):stage}
  deploymentBucket:
    name: ${file(serverless-common.yml):appname}.${file(serverless-common.yml):deploymentBucketPath.${self:provider.stage}, file(serverless-common.yml):deploymentBucketPath.default}.${self:provider.region}.deploys

custom:
  deploy:
    prod: prod
    default: dev

resources:
  Parameters:
    ExampleTableName:
      Type: String
      Default: Example-${self:provider.stage}
  Resources:
    ExampleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: !Ref ExampleTableName
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
          - AttributeName: Name
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
          - AttributeName: Name
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
  Outputs:
    ExampleTableName:
      Value: !Ref ExampleTable
      Export:
        Name: ExampleTableName-${self:provider.stage}
    ExampleTableArn:
      Value: !GetAtt ExampleTable.Arn
      Export:
        Name: ExampleTableArn-${self:provider.stage}
    ExampleTableStreamArn:
      Value: !GetAtt ExampleTable.StreamArn
      Export:
        Name: ExampleTableStreamArn-${self:provider.stage}