service: s3

provider:
  name: aws
  region: ${file(serverless-common.yml):region}
  stage: ${file(serverless-common.yml):stage}
  deploymentBucket:
    name: ${file(serverless-common.yml):appname}.${file(serverless-common.yml):deploymentBucketPath.${self:provider.stage}, file(serverless-common.yml):deploymentBucketPath.default}.${self:provider.region}.deploys

resources:
  Resources:
    ExampleBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: slsopsexample-bucket-${self:provider.stage}
  Outputs:
    ExampleBucketName:
      Value: !Ref ExampleBucket
      Export:
        Name: ExampleBucketName-${self:provider.stage}